spring.application.name=SMS
 spring.datasource.url= jdbc:postgresql://localhost:5432/your postgres database name
                        spring.datasource.username= // your postgres username
                        spring.datasource.password=  //your postgres password
                        
                        spring.jpa.hibernate.ddl-auto=update
                        spring.jpa.properties.hibernate.format_sql=true
                        spring.jpa.show-sql=true
                        
                        spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
